
all: tolower count compute finalize read

tolower: tolower.c
	gcc -o tolower tolower.c -O9

count: count.c
	gcc -o count count.c -O9

compute: compute.c
	gcc -o compute compute.c -O9 -lm

finalize: finalize.c
	gcc -o finalize finalize.c -O9 -lm

read: read.c
	gcc -o read read.c -O9 -lm
