#!/bin/tcsh
# convertdir $1 $2 converts db directory $1 from ascii to binary in $2
set cur=`pwd`
rm -rf $2
mkdir $2
cd $2
set trg=`pwd`
cd $cur
cd $1
foreach i (*)
$cur/convert $i $trg/$i
end
cd $cur
